modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mod_xrt"
version="1.0.0"
displayName="mod Xrt"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="famille, MCreator"

[[dependencies.mod_xrt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




